"""Add File Versioning

Revision ID: f7dfc96449be
Revises: 04257e619113
Create Date: 2026-01-14 10:13:52.987962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dfc96449be'
down_revision: Union[str, Sequence[str], None] = '04257e619113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('version_num', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_versions_id'), 'file_versions', ['id'], unique=False)
    op.add_column('files', sa.Column('is_checked_out', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('checked_out_by_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('checked_out_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'files', 'users', ['checked_out_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'checked_out_at')
    op.drop_column('files', 'checked_out_by_id')
    op.drop_column('files', 'is_checked_out')
    op.drop_index(op.f('ix_file_versions_id'), table_name='file_versions')
    op.drop_table('file_versions')
    # ### end Alembic commands ###
